a_b_plugin:
  repo: git@github.com:winton/a_b_plugin.git
  path: vendor
delayed_job:
  repo: git://github.com/collectiveidea/delayed_job.git
  path: vendor
deploy:
  repo: git@github.com:br/a_b_deploy.git
  path: config